# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.TQDMProgressBar.html#lightning.pytorch.callbacks.TQDMProgressBar

tqdm:
  _target_: lightning.pytorch.callbacks.TQDMProgressBar
  leave: true