# @package _global_

defaults:
  - _self_
  - data: cora # choose datamodule with `test_dataloader()` for evaluation
  - model: cora
  - logger: many_loggers
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
