# @package _global_

defaults:
  - _self_
  - data: mutag
  - model: graph_pred
  - logger: csv
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

seed: 1234

# these are needed by the graph prediction of MUTAG data
# see: https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.datasets.TUDataset.html
model:
  num_features: 7
  num_classes: 2

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
